version: "3.9"
services:
  redis:
    image: redis:latest
    command: redis-server --requirepass admin
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/redis/trafik/new

volumes:
  redis_data:

networks:
  local:
    name: local
    driver: bridge

