version: "3.9"
services:
  redis:
    image: redis:latest
    command: redis-server
    ports:
      - "6389:6379"
    volumes:
      - redis_data:/data/redis/trafiklab

volumes:
  redis_data:

networks:
  local:
    name: local
    driver: bridge

